trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildDeploy
  displayName: Deploy Splunk Apps
  strategy:
    matrix:
      App1:
        APP_NAME: "app1"
        APP_PATH: "apps/app1"
      App2:
        APP_NAME: "app2"
        APP_PATH: "apps/app2"
  steps:
    - script: echo "Deploying $(APP_NAME) from $(APP_PATH)"
      displayName: "Deploy $(APP_NAME)"
