trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildDeploy
  displayName: Deploy Splunk Apps
  strategy:
    matrix:
      App1:
        APP_NAME: "app1"
        APP_PATH: "apps/app1"
      App2:
        APP_NAME: "app2"
        APP_PATH: "apps/app2"
  steps:
    - script: |
        echo "Deploying Splunk App: $(APP_NAME)"
        curl -k -u $(SPLUNK_USER):$(SPLUNK_PASSWORD) \
          https://$(SPLUNK_HOST):8089/services/apps/local \
          -F "name=@$(APP_PATH)/app.spl" \
          -F "update=true"
      displayName: "Install $(APP_NAME) on Splunk"
