trigger:
  branches:
    include:
      - main

variables:
  SPLUNK_BASE_URL: 'https://9.223.112.231:8089/'
  SPLUNK_AUTH_HEADER: 'Authorization: Bearer $(SPLUNK_TOKEN)'

stages:
  - stage: BuildAndDeployApps
    jobs:
      - job: LoopApps
        strategy:
          matrix:
            app1:
              APP_NAME: 'app1'
            app2:
              APP_NAME: 'app2'
        steps:
          - template: templates/build-deploy.yml
            parameters:
              appName: ${{ matrix.APP_NAME }}
